server:
  modt: "&5[&2UHC&3-&419hAuLit&5]&7 1.8 -> 1.16\n&8Discord GottaGras Gaming: &6https://discord.gg/yeBv85Mt5z"
world:
  #True: La map uhc est regenere | False: La map uhc n'est pas regenere
  gen_start: false
  hub:
    x: -0.5
    y: 33
    z: -18.5
message:
  prefix: "&5[&2UHC&3-&419hAuLit&5]&7 "
uhc:
  # Tout les temps suivants sont en secondes
  map_size: 1500
  final_map_size: 100
  time_invincible: 30
  time_final_heal: 1200
  time_pvp: 1200
  time_border: 3600
  time_end_border: 4800
scenario:
  # True ou False
  cutclean: true
  # Mettre un chiffre
  xp_rate: 5
  fireless: true
  nofall: false
  all_tree_drop: true
  # Mettre le pourcentage de change
  apple_rate: 2
